# USAGE:
#
#   docker-compose build sdk
#   USER_ID=$UID docker-compose up build
#   ESPPORT=/dev/ttyUSB? docker-compose up flash
#   ESPPORT=/dev/ttyUSB? docker-compose run --rm monitor
#
# @see https://docs.espressif.com/projects/esp8266-rtos-sdk/en/latest/get-started/index.html#environment-variables

version: '3.8'
services:
  sdk:
    image: qmsk/esp8266-sdk
    build:
      context: sdk
      args:
        ESP8266_RTOS_SDK_VERSION: v3.4-rc

  build:
    image: qmsk/esp8266-sdk
    volumes:
      - .:/build
    working_dir: /build
    user: "${USER_ID:-1000}"
    command: make
    init: true

  flash:
    image: qmsk/esp8266-sdk
    volumes:
      - .:/build
    working_dir: /build
    user: build
    command: make flash
    init: true
    devices:
      - "${ESPPORT}"
    environment:
      ESPPORT: "${ESPPORT}"

  monitor:
    image: qmsk/esp8266-sdk
    volumes:
      - .:/build
    working_dir: /build
    user: build
    command: make monitor MONITOR_OPTS="--baud $${MONITORBAUD} --port $${ESPPORT} --eol CRLF"
    init: true
    devices:
      - "${ESPPORT}"
    environment:
      ESPPORT: "${ESPPORT}"
      MONITORBAUD: 74880

  npm:
    image: qmsk/esp8266-web
    build:
      context: web
    volumes:
      - ./web:/build/web
    user: "${USER_ID:-1000}"
    working_dir: /build/web
    entrypoint: npm
    environment:
      API_URL: $API_URL
    network_mode: host
