# USAGE:
#
#   USER_ID=$UID docker-compose up build
#   TTY_DEV=/dev/ttyUSB? docker-compose up flash
#   TTY_DEV=/dev/ttyUSB? docker-compose run --rm console

version: '3.8'
services:
  sdk:
    image: esp8266/sdk:3.4-rc
    build:
      context: sdk
      args:
        ESP8266_RTOS_SDK_VERSION: v3.4-rc
    volumes:
      - .:/build
    user: "${USER_ID:-1000}"
    command: make

  flash:
    image: esp8266/sdk:3.4-rc
    volumes:
      - .:/build
    working_dir: /build
    user: build
    command: make flash
    devices:
      - "${ESPPORT}"
    environment:
      ESPPORT: "${ESPPORT}"

  monitor:
    image: esp8266/sdk:3.4-rc
    volumes:
      - .:/build
    working_dir: /build
    user: build
    command: make monitor
    devices:
      - "${ESPPORT}"
    environment:
      ESPPORT: "${ESPPORT}"

  npm:
    image: esp8266/web
    build:
      context: web
    volumes:
      - ./web:/build/web
    user: "${USER_ID:-1000}"
    working_dir: /build/web
    entrypoint: npm
    environment:
      API_URL: $API_URL
    network_mode: host
