version: '3.8'
services:
  sdk:
    image: qmsk/esp-idf
    build:
      context: ../../sdk/esp-idf
      args:
        ESP_IDF_VERSION: v4.3.1
    command: idf.py --version

  build:
    image: qmsk/esp-idf
    volumes:
      - ../..:/build
    working_dir: /build/projects/esp32
    user: "${USER_ID:-1000}"
    command: idf.py build
    init: true
