version: '3.8'
services:
  sdk:
    image: qmsk/esp-idf
    build:
      context: ../../sdk/esp-idf
      args:
        ESP_IDF_VERSION: v4.3.1
        BUILD_UID: ${BUILD_UID}
        BUILD_GID: ${BUILD_GID}
    command: idf.py --version

  build:
    image: qmsk/esp-idf
    volumes:
      - ../..:/build
    working_dir: /build/projects/esp32
    command: idf.py build
    init: true

  flash:
    image: qmsk/esp-idf
    volumes:
      - ../..:/build
    working_dir: /build/projects/esp32
    command: idf.py flash
    init: true
    devices:
      - "${ESPPORT}"
    environment:
      ESPPORT: "${ESPPORT}"

  monitor:
    image: qmsk/esp-idf
    volumes:
      - ../..:/build
    working_dir: /build/projects/esp32
    command: idf.py monitor
    init: true
    devices:
      - "${ESPPORT}"
    environment:
      ESPPORT: "${ESPPORT}"
