# USAGE:
#
#   docker-compose build sdk
#   USER_ID=$UID docker-compose up build
#   ESPPORT=/dev/ttyUSB? docker-compose up flash
#   ESPPORT=/dev/ttyUSB? docker-compose run --rm monitor
#   ESPPORT=/dev/ttyUSB? docker-compose up config-reset
#
# @see https://docs.espressif.com/projects/esp8266-rtos-sdk/en/latest/get-started/index.html#environment-variables
#
#
#   USER_ID=$UID docker-compose run --rm npm install
#   USER_ID=$UID docker-compose run --rm npm run build
#   USER_ID=$UID API_URL=http://172.29.16.47 docker-compose run --rm npm start

version: '3.8'
services:
  sdk:
    image: qmsk/esp8266-rtos-sdk
    build:
      context: ../../sdk/esp8266-rtos-sdk
      args:
        ESP8266_RTOS_SDK_VERSION: v3.4

  build:
    image: qmsk/esp8266-rtos-sdk
    volumes:
      - ../..:/build
    working_dir: /build/projects/esp8266
    user: "${USER_ID:-1000}"
    command: make
    init: true

  flash:
    image: qmsk/esp8266-rtos-sdk
    volumes:
      - ../..:/build
    working_dir: /build/projects/esp8266
    user: build
    command: make flash
    init: true
    devices:
      - "${ESPPORT}"
    environment:
      ESPPORT: "${ESPPORT}"

  config-reset:
    image: qmsk/esp8266-rtos-sdk
    volumes:
      - ../..:/build
    working_dir: /build/projects/esp8266
    user: build
    command: make config-reset
    init: true
    devices:
      - "${ESPPORT}"
    environment:
      ESPPORT: "${ESPPORT}"

  monitor:
    image: qmsk/esp8266-rtos-sdk
    volumes:
      - ../..:/build
    working_dir: /build/projects/esp8266
    user: build
    command: make monitor MONITOR_OPTS="--baud $${MONITORBAUD} --port $${ESPPORT} --eol CRLF"
    init: true
    devices:
      - "${ESPPORT}"
    environment:
      ESPPORT: "${ESPPORT}"
      MONITORBAUD: "${MONITORBAUD:-115200}"

  npm:
    image: qmsk/esp-web
    build:
      context: ../../web
    volumes:
      - ../..:/build
    user: "${USER_ID:-1000}"
    working_dir: /build/web
    entrypoint: npm
    environment:
      API_URL: $API_URL
    network_mode: host
