name: Build

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build-esp32:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup
        run: |
          echo "BUILD_UID=$(id -u)" >> $GITHUB_ENV
          echo "BUILD_GID=$(id -g)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build SDK
        run: docker-compose -f projects/esp32/docker-compose.yml build sdk

      - name: Build
        run: docker-compose -f projects/esp32/docker-compose.yml run --rm build
