name: Build

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build-web:
    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: web

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 15.x

      - name: Install
        run: npm ci

      - name: Builld
        run: npm run build

  # requires web/dist directory to exist
  build-esp32:
    needs:
      - build-web
    runs-on: ubuntu-20.04
    steps:
      - name: Setup
        run: |
          echo "BUILD_UID=$(id -u)" >> $GITHUB_ENV
          echo "BUILD_GID=$(id -g)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build SDK
        run: docker-compose -f projects/esp32/docker-compose.yml build sdk

      - name: Build
        run: docker-compose -f projects/esp32/docker-compose.yml run --rm build
