name: Build

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build-web:
    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: web

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 15.x

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: web-dist
          path: web/dist/
          if-no-files-found: error

  # requires web/dist directory to exist
  build-esp32:
    needs:
      - build-web
    runs-on: ubuntu-20.04
    steps:
      - name: Setup
        run: |
          echo "BUILD_UID=$(id -u)" >> $GITHUB_ENV
          echo "BUILD_GID=$(id -g)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Download web-dist
        uses: actions/download-artifact@v3
        with:
          name: web-dist
          path: web/dist

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Build SDK
        run: docker-compose -f projects/esp32/docker-compose.yml build sdk

      - name: Build
        run: docker-compose -f projects/esp32/docker-compose.yml run --rm build
